name: "n0s1"

on:
  schedule:
    - cron: '0 13 * * 1'
  workflow_dispatch:

jobs:
  jira_secret_scanning:
    permissions: write-all
    runs-on: [ubuntu-latest]
    steps:
      - uses: spark1security/n0s1-action@main
        env:
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
          CONFLUENCE_EMAIL: ${{ vars.CONFLUENCE_EMAIL }}
          CONFLUENCE_SERVER: ${{ vars.CONFLUENCE_SERVER }}
        with:
          scan-target: 'confluence_scan'
          report-format: "sarif"
          report-file: "confluence_secret_report.sarif"
          timeout: 60
          limit: 250
          scope: "cql: space=\"ACC\" AND type=page "
      - name: Display SARIF result
        run: |
          cat confluence_secret_report.sarif | jq | head -n 20
          cat confluence_secret_report.sarif | jq | tail -n 20
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "confluence_secret_report.sarif"